### ISSUE TITLE
Agregar labels para etiquetar issues según el tipo de trabajo requerido

### ISSUE THREAD

**Issue by rolivencia** [frontendcafe/sunrise-cafe#46]
Tomando como ejemplo el proyecto [La Cuentoneta](https://github.com/cuentoneta/cuentoneta/issues/labels), se requiere poseer un conjunto de etiquetas que permitan categorizar el tipo de trabajo de las incidencias del proyecto.

Deben agregarse estas etiquetas al proyecto para, a partir de ahí, someter a evaluación del equipo cualquier posible mejora o corrección.

**Comment by sarganar** [comment]
este issue es similar al #44 ?

**Comment by JoeOsG** [comment]
Pareciera que sí.
@rolivencia 

https://github.com/frontendcafe/sunrise-cafe/issues/46
![{A46E6FBD-9BC6-4D15-B73D-30A5A82D8423}](https://github.com/user-attachments/assets/3351dcd8-c777-4951-b86c-ba38a46a5737)

**Comment by rolivencia** [comment]
> este issue es similar al #44 ?

No, no lo son. Uno representa al agregado de labels asignables, el otro a la asignación de esos labels a los issues abiertos.

Luego de controlar que tenemos todos los labels necesarios, procedí a cerrar #44. Veo que todos los issues tienen su correspondiente label, por lo que creo que también podríamos cerrar este issue @JoeOsG .

**Comment by JoeOsG** [comment]
Enterado.

**Comment by sarganar** [comment]
Genial
