### ISSUE TITLE
Hacer responsive el login

### ISSUE THREAD

**Issue by Durphan** [frontendcafe/sunrise-cafe#47]
El login de momento no es responsive, lo que se podria hacer para convertirlo en responsive es utilizar una media query el cual basandonos en el tamaño de pantalla del usuario, se elimine la imagen del barista con el cafe, la cual ocupa mucho espacio, de forma que se muestre solamente el input del password, del login y el navbar, el cual debe verse si va a tener que hacerse una version responsive tambien.

**Comment by dylanson25** [comment]
Puedo tomarlo?

**Comment by JoeOsG** [comment]
> Puedo tomarlo?

¡Adelante!

**Comment by sarganar** [comment]
Esto creo ya se completó.

**Comment by JoeOsG** [comment]
Trabajado en:
https://github.com/frontendcafe/sunrise-cafe/pull/54
